### ISSUE TITLE
Est-ce que ':=' doit être un operateur avec priorité ou bien pas un operateur ?

### ISSUE THREAD

**Issue by AubryH** [damien-gerard/cei2014#8]
a:=1+2 
est parsé en l'ast : 
+(:=(a,1),2)

**Comment by damien-gerard** [comment]
Dans le langage 4D := est plus un statement qu'une expr. On ne peut donc pas ecrire foo($a:=10) par exemple.
L'ast doit etre le suivant : 
 * assignment
         [lhs] a
         [rhs] (1+2)
On ne peut pas avoir a:=1, puis ensuite a+=2. Ce n'est pas equivalent.
